---
- hosts: all
  vars:
    - ansible_network_os: nokia.sros.classic
    - ansible_host_key_auto_add: yes
    - ansible_host_key_checking: False
    - ignore_errors : true

  connection: network_cli
  gather_facts: No

  collections:
  - nokia.sros

  tasks:
  - name: get device info
    device_info:
    register: device_info

  - name: display device info
    debug:
      msg: |
        {{device_info.output}}
...
