---
- hosts: all
  vars:
    - ansible_network_os: nokia.sros.classic
    - ansible_host_key_auto_add: yes
    - ansible_host_key_checking: False

  connection: network_cli
  gather_facts: No

  collections:
  - nokia.sros

  tasks:
  - name: do some config
    cli_config:
      config: |
        configure port 1/1/3 no shutdown
...
