---
- hosts: all
  vars:
   - ansible_network_os: nokia.sros.classic
   - ansible_host_key_auto_add: true
   - ansible_host_key_checking: false
   
  connection: network_cli
  gather_facts: false
  
  collections:
  - nokia.sros
  - ansible.netcommon
  
  tasks:
  - name: get system information
    cli_command:
      command: show system information
    register: output1

  - name: display output
    debug:
      msg: |
        {{output1.stdout}}
...
