---
- hosts: all
  vars:
   - ansible_network_os: sros
   - ansible_host_key_auto_add: true
   - ansible_host_key_checking: false
   - ssh_args: '-o KexAlgorithms=diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss'
   
  connection: network_cli
  gather_facts: false


  tasks:
  - name: get system information
    sros_command:
      commands: show system information
    register: output1

  - name: display output
    debug:
      msg: |
        {{output1.stdout}}
...
