---
- hosts: all
  vars:
    - ansible_host_key_cheking: false
  tasks:
  - name: get system information
    ansible.netcommon.cli_command:
      command: show system information
    register: output1

  - name: file dir (classic)
    ansible.netcommon.cli_command:
      command: file dir
    register: output2

  - name: show version
    ansible.netcommon.cli_command:
      command: show version
    register: output3

  - name: reboot node (abort)
    ansible.netcommon.cli_command:
      command: admin reboot
      prompt:
        - "Are you sure you want to reboot (y/n)?"
      answer:
        - 'n'
    register: output4

  - name: display output
    debug:
      msg: |
        {{output1.stdout}}
        {{output2.stdout}}
        {{output3.stdout}}
        {{output4.stdout}}
...
