---
- hosts: all
  vars:
    - ansible_network_os: nokia.sros.light
    - ansible_host_key_auto_add: yes
    - ansible_host_key_checking: False

  connection: network_cli
  gather_facts: No

  collections:
  - nokia.sros

  tasks:
#  - name: generate config
#    template:
#      src: add_address.j2
#      dest: "/runner/project/config/{{ routers.router_name }}.txt"

  - name: print
    debug:
      msg: |
        {{ lookup('template', 'add_address.j2') }}
        
  - name: do some config
    cli_config:
      config: |
        {{ lookup('template', 'add_address.j2') }}
...
